import json
import os
from copy import deepcopy
from pathlib import Path


STATIC_VOICE_CATALOG = {
    "version": "2026-09-01",
    "defaults": {
        "language": "en",
        "timezone": "UTC",
        "stt": {"provider": "deepgram", "model": "nova-3"},
        "llm": {
            "provider": "deepseek",
            "model": "deepseek-chat",
            "fallback_model": "deepseek-chat",
        },
        "tts": {
            "provider": "deepgram",
            "model": "aura-2",
            "voice": "aura-2-asteria-en",
        },
    },
    "languages": [
        {"id": "en", "label": "English", "locale": "en-US"},
        {"id": "hi", "label": "Hindi", "locale": "hi-IN"},
        {"id": "en-IN", "label": "English (India)", "locale": "en-IN"},
        {"id": "ta", "label": "Tamil", "locale": "ta-IN"},
        {"id": "te", "label": "Telugu", "locale": "te-IN"},
        {"id": "kn", "label": "Kannada", "locale": "kn-IN"},
        {"id": "ml", "label": "Malayalam", "locale": "ml-IN"},
        {"id": "es", "label": "Spanish", "locale": "es-ES"},
        {"id": "fr", "label": "French", "locale": "fr-FR"},
        {"id": "de", "label": "German", "locale": "de-DE"},
        {"id": "pt", "label": "Portuguese", "locale": "pt-BR"},
        {"id": "ar", "label": "Arabic", "locale": "ar-SA"},
        {"id": "ja", "label": "Japanese", "locale": "ja-JP"},
        {"id": "zh", "label": "Chinese (Mandarin)", "locale": "zh-CN"},
    ],
    "timezones": [
        "UTC",
        "Asia/Kolkata",
        "Asia/Dubai",
        "Asia/Singapore",
        "Asia/Tokyo",
        "Asia/Shanghai",
        "America/New_York",
        "America/Chicago",
        "America/Los_Angeles",
        "America/Sao_Paulo",
        "Europe/London",
        "Europe/Paris",
        "Europe/Berlin",
        "Australia/Sydney",
    ],
    "stt_models": [
        # ── Deepgram ──────────────────────────────────────────────────────────
        {
            "provider": "deepgram",
            "id": "nova-3",
            "label": "Deepgram Nova-3",
            "languages": ["en", "en-IN", "es", "fr", "de", "pt", "ja", "zh"],
            "runtime_model": "nova-3",
            "billing_model": "deepgram/nova-3",
        },
        {
            "provider": "deepgram",
            "id": "nova-3-multilingual",
            "label": "Deepgram Nova-3 Multilingual",
            "languages": ["en", "en-IN", "hi", "es", "fr", "de", "pt", "ar"],
            "runtime_model": "nova-3",
            "runtime_language": "multi",
            "billing_model": "deepgram/nova-3-multilingual",
        },
        {
            "provider": "deepgram",
            "id": "nova-2",
            "label": "Deepgram Nova-2",
            "languages": ["en", "en-IN"],
            "runtime_model": "nova-2",
            "billing_model": "deepgram/nova-2",
        },
        # ── Sarvam (Indian languages) ────────────────────────────────────────
        {
            "provider": "sarvam",
            "id": "saaras:v3",
            "label": "Sarvam Saaras v3",
            "languages": ["hi", "en-IN", "ta", "te", "kn", "ml"],
            "runtime_model": "saaras:v3",
            "billing_model": "sarvam/saaras:v3",
        },
        # ── OpenAI Whisper ───────────────────────────────────────────────────
        {
            "provider": "openai",
            "id": "whisper-1",
            "label": "OpenAI Whisper-1",
            "languages": ["en", "hi", "es", "fr", "de", "pt", "ar", "ja", "zh", "en-IN"],
            "runtime_model": "whisper-1",
            "billing_model": "openai/whisper-1",
        },
    ],
    "llm_models": [
        # ── AWS Bedrock (Claude via AWS) ─────────────────────────────────────
        {
            "provider": "bedrock",
            "id": "us.anthropic.claude-haiku-4-5-20251001-v1:0",
            "label": "Claude Haiku 4.5 (AWS Bedrock)",
            "runtime_model": "us.anthropic.claude-haiku-4-5-20251001-v1:0",
            "billing_model": "bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0",
            "streaming": True,
        },
        {
            "provider": "bedrock",
            "id": "us.anthropic.claude-sonnet-4-5-20250929-v1:0",
            "label": "Claude Sonnet 4.5 (AWS Bedrock)",
            "runtime_model": "us.anthropic.claude-sonnet-4-5-20250929-v1:0",
            "billing_model": "bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0",
            "streaming": True,
        },
        {
            "provider": "bedrock",
            "id": "us.amazon.nova-micro-v1:0",
            "label": "Amazon Nova Micro",
            "runtime_model": "us.amazon.nova-micro-v1:0",
            "billing_model": "bedrock/us.amazon.nova-micro-v1:0",
            "streaming": True,
        },
        {
            "provider": "bedrock",
            "id": "us.amazon.nova-lite-v1:0",
            "label": "Amazon Nova Lite",
            "runtime_model": "us.amazon.nova-lite-v1:0",
            "billing_model": "bedrock/us.amazon.nova-lite-v1:0",
            "streaming": True,
        },
        # ── OpenAI ───────────────────────────────────────────────────────────
        {
            "provider": "openai",
            "id": "gpt-4o-mini",
            "label": "GPT-4o Mini",
            "runtime_model": "gpt-4o-mini",
            "billing_model": "openai/gpt-4o-mini",
            "streaming": True,
        },
        {
            "provider": "openai",
            "id": "gpt-4o",
            "label": "GPT-4o",
            "runtime_model": "gpt-4o",
            "billing_model": "openai/gpt-4o",
            "streaming": True,
        },
        {
            "provider": "openai",
            "id": "gpt-4.1-mini",
            "label": "GPT-4.1 Mini",
            "runtime_model": "gpt-4.1-mini",
            "billing_model": "openai/gpt-4.1-mini",
            "streaming": True,
        },
        # ── Groq (ultra-low latency) ─────────────────────────────────────────
        {
            "provider": "groq",
            "id": "llama-3.3-70b-versatile",
            "label": "Llama 3.3 70B (Groq)",
            "runtime_model": "llama-3.3-70b-versatile",
            "billing_model": "groq/llama-3.3-70b-versatile",
            "streaming": True,
        },
        {
            "provider": "groq",
            "id": "llama-3.1-8b-instant",
            "label": "Llama 3.1 8B Instant (Groq)",
            "runtime_model": "llama-3.1-8b-instant",
            "billing_model": "groq/llama-3.1-8b-instant",
            "streaming": True,
        },
        {
            "provider": "groq",
            "id": "gemma2-9b-it",
            "label": "Gemma 2 9B (Groq)",
            "runtime_model": "gemma2-9b-it",
            "billing_model": "groq/gemma2-9b-it",
            "streaming": True,
        },
        # ── DeepSeek ─────────────────────────────────────────────────────────
        {
            "provider": "deepseek",
            "id": "deepseek-chat",
            "label": "DeepSeek Chat (V3)",
            "runtime_model": "deepseek-chat",
            "billing_model": "deepseek/deepseek-chat",
            "streaming": True,
        },
        {
            "provider": "deepseek",
            "id": "deepseek-reasoner",
            "label": "DeepSeek Reasoner (R1)",
            "runtime_model": "deepseek-reasoner",
            "billing_model": "deepseek/deepseek-reasoner",
            "streaming": True,
        },
    ],
    "tts_models": [
        # ── Deepgram ──────────────────────────────────────────────────────────
        {
            "provider": "deepgram",
            "id": "aura-2",
            "label": "Deepgram Aura-2",
            "languages": ["en"],
            "runtime_model": "aura-2",
            "billing_model": "deepgram/aura-2",
        },
        # ── ElevenLabs ───────────────────────────────────────────────────────
        {
            "provider": "elevenlabs",
            "id": "eleven_flash_v2_5",
            "label": "ElevenLabs Flash v2.5",
            "languages": ["en", "en-IN", "hi", "es", "fr", "de", "pt", "ar", "ja", "zh"],
            "runtime_model": "eleven_flash_v2_5",
            "billing_model": "elevenlabs/eleven_flash_v2_5",
        },
        {
            "provider": "elevenlabs",
            "id": "eleven_turbo_v2_5",
            "label": "ElevenLabs Turbo v2.5",
            "languages": ["en", "en-IN", "hi", "es", "fr", "de", "pt"],
            "runtime_model": "eleven_turbo_v2_5",
            "billing_model": "elevenlabs/eleven_turbo_v2_5",
        },
        {
            "provider": "elevenlabs",
            "id": "eleven_multilingual_v2",
            "label": "ElevenLabs Multilingual v2",
            "languages": ["en", "en-IN", "hi", "es", "fr", "de", "pt", "ar", "ja", "zh"],
            "runtime_model": "eleven_multilingual_v2",
            "billing_model": "elevenlabs/eleven_multilingual_v2",
        },
        # ── Sarvam ───────────────────────────────────────────────────────────
        {
            "provider": "sarvam",
            "id": "bulbul:v3",
            "label": "Sarvam Bulbul v3",
            "languages": ["hi", "en-IN", "ta", "te", "kn", "ml"],
            "runtime_model": "bulbul:v3",
            "billing_model": "sarvam/bulbul:v3",
        },
        # ── Cartesia ─────────────────────────────────────────────────────────
        {
            "provider": "cartesia",
            "id": "sonic-2",
            "label": "Cartesia Sonic-2",
            "languages": ["en", "es", "fr", "de", "pt", "ja", "zh"],
            "runtime_model": "sonic-2",
            "billing_model": "cartesia/sonic-2",
        },
        {
            "provider": "cartesia",
            "id": "sonic-2-multilingual",
            "label": "Cartesia Sonic-2 Multilingual",
            "languages": ["en", "hi", "en-IN", "es", "fr", "de", "pt", "ar"],
            "runtime_model": "sonic-2",
            "billing_model": "cartesia/sonic-2-multilingual",
        },
    ],
    "voices": [
        # ── Deepgram Aura-2 ───────────────────────────────────────────────────
        {
            "provider": "deepgram",
            "id": "aura-2-asteria-en",
            "label": "Asteria (F)",
            "languages": ["en"],
            "tts_models": ["aura-2"],
            "runtime_voice": "aura-2-asteria-en",
        },
        {
            "provider": "deepgram",
            "id": "aura-2-athena-en",
            "label": "Athena (F)",
            "languages": ["en"],
            "tts_models": ["aura-2"],
            "runtime_voice": "aura-2-athena-en",
        },
        {
            "provider": "deepgram",
            "id": "aura-2-apollo-en",
            "label": "Apollo (M)",
            "languages": ["en"],
            "tts_models": ["aura-2"],
            "runtime_voice": "aura-2-apollo-en",
        },
        {
            "provider": "deepgram",
            "id": "aura-2-thalia-en",
            "label": "Thalia (F)",
            "languages": ["en"],
            "tts_models": ["aura-2"],
            "runtime_voice": "aura-2-thalia-en",
        },
        {
            "provider": "deepgram",
            "id": "aura-2-orion-en",
            "label": "Orion (M)",
            "languages": ["en"],
            "tts_models": ["aura-2"],
            "runtime_voice": "aura-2-orion-en",
        },
        {
            "provider": "deepgram",
            "id": "aura-2-luna-en",
            "label": "Luna (F)",
            "languages": ["en"],
            "tts_models": ["aura-2"],
            "runtime_voice": "aura-2-luna-en",
        },
        # ── ElevenLabs ───────────────────────────────────────────────────────
        {
            "provider": "elevenlabs",
            "id": "EXAVITQu4vr4xnSDxMaL",
            "label": "Sarah (F)",
            "languages": ["en", "en-IN", "hi", "es", "fr", "de", "pt", "ar", "ja", "zh"],
            "tts_models": ["eleven_flash_v2_5", "eleven_turbo_v2_5", "eleven_multilingual_v2"],
            "runtime_voice": "EXAVITQu4vr4xnSDxMaL",
        },
        {
            "provider": "elevenlabs",
            "id": "UgBBYS2sOqTuMpoF3BR0",
            "label": "Mark (M)",
            "languages": ["en", "en-IN", "es", "fr", "de", "pt"],
            "tts_models": ["eleven_flash_v2_5", "eleven_turbo_v2_5", "eleven_multilingual_v2"],
            "runtime_voice": "UgBBYS2sOqTuMpoF3BR0",
        },
        {
            "provider": "elevenlabs",
            "id": "cgSgspJ2msm6clMCkdW9",
            "label": "Jessica (F)",
            "languages": ["en", "en-IN", "hi", "es", "fr", "de", "pt", "ar", "ja", "zh"],
            "tts_models": ["eleven_flash_v2_5", "eleven_turbo_v2_5", "eleven_multilingual_v2"],
            "runtime_voice": "cgSgspJ2msm6clMCkdW9",
        },
        {
            "provider": "elevenlabs",
            "id": "nPczCjzI2devNBz1zQrb",
            "label": "Brian (M)",
            "languages": ["en", "en-IN", "es", "fr", "de"],
            "tts_models": ["eleven_flash_v2_5", "eleven_turbo_v2_5", "eleven_multilingual_v2"],
            "runtime_voice": "nPczCjzI2devNBz1zQrb",
        },
        # ── Sarvam ───────────────────────────────────────────────────────────
        {
            "provider": "sarvam",
            "id": "shubh",
            "label": "Shubh (M)",
            "languages": ["hi", "en-IN", "ta", "te", "kn", "ml"],
            "tts_models": ["bulbul:v3"],
            "runtime_voice": "shubh",
        },
        {
            "provider": "sarvam",
            "id": "ananya",
            "label": "Ananya (F)",
            "languages": ["hi", "en-IN", "ta", "te", "kn", "ml"],
            "tts_models": ["bulbul:v3"],
            "runtime_voice": "ananya",
        },
        {
            "provider": "sarvam",
            "id": "diya",
            "label": "Diya (F)",
            "languages": ["hi", "en-IN"],
            "tts_models": ["bulbul:v3"],
            "runtime_voice": "diya",
        },
        # ── Cartesia ─────────────────────────────────────────────────────────
        {
            "provider": "cartesia",
            "id": "a0e99841-438c-4a64-b679-ae501e7d6091",
            "label": "Barbershop Man (M)",
            "languages": ["en", "es", "fr", "de", "pt", "ja", "zh", "hi", "en-IN", "ar"],
            "tts_models": ["sonic-2", "sonic-2-multilingual"],
            "runtime_voice": "a0e99841-438c-4a64-b679-ae501e7d6091",
        },
        {
            "provider": "cartesia",
            "id": "79a125e8-cd45-4c13-8a67-188112f4dd22",
            "label": "British Reading Lady (F)",
            "languages": ["en", "es", "fr", "de", "pt", "ja", "zh", "hi", "en-IN", "ar"],
            "tts_models": ["sonic-2", "sonic-2-multilingual"],
            "runtime_voice": "79a125e8-cd45-4c13-8a67-188112f4dd22",
        },
    ],
}


def load_voice_catalog():
    catalog_path = os.getenv("VOICE_CATALOG_PATH")
    if catalog_path:
        return json.loads(Path(catalog_path).read_text())
    return deepcopy(STATIC_VOICE_CATALOG)
